sudo: false
language: node_js
node_js:
  - "node"
  - "lts/*"
services:
  - xvfb
os:
  - linux
  - osx
  # - windows # Enable once https://github.com/microsoft/vscode/issues/77499 is fixed
addons:
  apt:
    packages:
      - libsecret-1-dev
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm test
  - npm list --production --parseable --depth=99999 # Check if can publish VSCode extension
  - npm run vscode:prepublish
  - git status
  - git diff
  - CHANGED_FILES=$(git diff --name-only | grep -v '^package-lock.json') || true
  - echo "Changed files:\n$CHANGED_FILES"
  - if [[ -z "${CHANGED_FILES// }" ]]; then echo "No changes!"; else exit 1; fi
